<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10480" started-at="2018-07-03T05:43:12Z" finished-at="2018-07-03T05:43:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10480" started-at="2018-07-03T05:43:12Z" finished-at="2018-07-03T05:43:22Z">
      <class name="com.qait.Mail.G_Mail.TestMail">
        <test-method status="PASS" signature="InitializeBrowser()[pri:0, instance:com.qait.Mail.G_Mail.TestMail@36b4cef0]" name="InitializeBrowser" is-config="true" duration-ms="4748" started-at="2018-07-03T05:43:12Z" finished-at="2018-07-03T05:43:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitializeBrowser -->
        <test-method status="PASS" signature="TestOpenGmail()[pri:0, instance:com.qait.Mail.G_Mail.TestMail@36b4cef0]" name="TestOpenGmail" duration-ms="2194" started-at="2018-07-03T05:43:16Z" finished-at="2018-07-03T05:43:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestOpenGmail -->
        <test-method status="FAIL" signature="CheckMenuItemForWork()[pri:1, instance:com.qait.Mail.G_Mail.TestMail@36b4cef0]" name="CheckMenuItemForWork" duration-ms="3515" started-at="2018-07-03T05:43:19Z" finished-at="2018-07-03T05:43:22Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
at com.qait.Mail.G_Mail.TestMail.CheckMenuItemForWork(TestMail.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckMenuItemForWork -->
      </class> <!-- com.qait.Mail.G_Mail.TestMail -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
